@apiKey = {{stripeApiKey}}
#@testCustomerId = cus_LHejWZ80NfdZkb
@testCustomerId = cus_LLOkMjkqbYnhCP


### Get customers
GET https://api.stripe.com/v1/customers?limit=100
Authorization: Bearer {{apiKey}}

### Get customer
GET https://api.stripe.com/v1/customers/{{testCustomerId}}
Authorization: Bearer {{apiKey}}


### Get subscriptions
GET https://api.stripe.com/v1/subscriptions?customer={{testCustomerId}}
Authorization: Bearer {{apiKey}}

### Get products
GET https://api.stripe.com/v1/products?active=true
Authorization: Bearer {{apiKey}}

### Get plans
GET https://api.stripe.com/v1/plans?active=true
Authorization: Bearer {{apiKey}}

### Update Customer
POST https://api.stripe.com/v1/customers/{{testCustomerId}}
Authorization: Bearer {{apiKey}}
Content-Type: application/x-www-form-urlencoded

description=XXXX